### ISSUE TITLE
Moving settings to a popup

### ISSUE THREAD

**Issue by juleshwar** [flawyte/fast-scroll#6]
Thank you for making this wonderful and elegant extension!
I started loving this feature on VS code and wanted the same experience on a web browser.

Regarding the settings, I felt it would be more accessible if it was moved as a popup. 

Tampermonkey extension for example
![image](https://user-images.githubusercontent.com/24788774/94558349-727e9d00-027d-11eb-8276-79aa47db846f.png)

I could make a PR with the said changes 😄

## Update
Check PR #7

**Comment by flawyte** [comment]
Hey! Thank you for opening this issue.

I'm open to suggestions, however two things cross my mind about moving the settings to a pop-up :

1. As you have seen the settings page has a certain amount of information that needs to be shown to the user so he can understand clearly what each setting is about and how it affects the extension's behavior, and I'm not sure everything can fit into a pop-up without removing some info or degrading the UX
2. Each setting is here because some users requested to be able to customize the extension's behavior more than version 1 offered, but the majority of them problably set these settings once when they download the extension the first time and never go back to this settings page again, so I don't think there's a clear user need for the settings to be more accessible

But I'll take a look at the PR and come back to you asap.

**Comment by juleshwar** [comment]
**1.** It was actually possible to include all the contents of the settings page into the popup. 
**1.** This point does make sense. I, myself, too haven't been to the settings page to re-configure my settings. But when I clicked on the extension for the first time, it took me time to get to the settings page because
**2.1** Chrome doesn't make it easy on the eyes to figure out which option to click to change the settings
![image](https://user-images.githubusercontent.com/24788774/94982901-f1b0f100-055b-11eb-864f-5d8085c957da.png)
The 'Options' here is not prominent enough. It looks like the option leads to some settings related to Chrome.
**2.2** I have used extensions in the past and it took me some time to figure out how to get to the extension settings because all of them have had a popup (That's my experience with extensions 😅).
